<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./library/style.css">
    <meta name="author" content="Florian Moreno">
    <title>Ajout Repas/Poids</title>
</head>

<body>

    <header>
        <h1><img src="./img/serpentlogo2.png" alt="Snake logo"> Ajouter <img src="./img/serpentlogo.png" alt="Snake logo"></h1>
    </header>

    <div class="box3">
        <select name="type" class="font">
            <option value="all">Tous</option>
            <option value="Snatch">Snatch</option>
            <option value="Nazca" selected>Nazca</option>
            <option value="Snow">Snow</option>
        </select>
    </div>

    <div class="type">Ajouter un repas :</div>

    <div id="container">
        <form action="" method="post">
            <!-- TO DO Mettre dans action le chemin de la page "??? a voir" -->

            <div class="box">
                <label for="date"> Date : </label>
                <input type="date" name="date" id="date">
            </div>
            <div class="box">
                <label for="type"> Type : </label>
                <select name="type" class="font">
                    <option value="adult">Rat adulte</option>
                    <option value="middle" selected>Rat moyen</option>
                    <option value="mouse">Souris</option>
                </select>
            </div>
            <div class="box">
                <input type="submit" id="size" value="Ok">
            </div>
    </div>
    </form>
    <div class="type">Ajouter un poids :</div>

    <div id="container">
        <form action="../Controller/ControllerWeight.php" method="post">
            <!-- TO DO Mettre dans action le chemin de la page "Resumer" -->

            <div class="box">
                <label for="date"> Date : </label>
                <input type="date" name="date" id="date">
            </div>
            <div class="bo">
                <label for="masse"> Poids : </label>
                <input type="text" name="masse" id="masse">
            </div>
            <div class="Gr">Gr</div>
            <input type="submit" id="size2" value="Ok">

    </div>
    </form>

</body>

</html>