<?php
require_once './ControllerDate.php';
?>
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./library/style.css">
    <meta name="author" content="Florian Moreno">
    <title>Consultation générale</title>
</head>
<header>
    <h1><img src="./img/logoSerpent2.png" alt="Snake logo"> Consultation <img src="./img/logoSerpent.png" alt="Snake logo"></h1>
</header>

<body>
    
        <div class="box3">
            <label for="firstname"></label>
            <select name="firstname" class="font">
                <option value="0" selected>Tous</option>
                <option value="1">Snatch</option>
                <option value="3">Nazca</option>
                <option value="2">Snow</option>
            </select>
        </div>

        <div class="type"> Derniers repas :</div>
        <div id="list" class="matchList">


            <table>
                <tr class="toHidden">
                    <th>Date du dernier repas</th>
                    <th class="tButton" colspan="3"></th>
                </tr>

                <?php foreach ($list as $match) : ?>
                    <tr>
                        <td> <?= $match['trueDate']; ?> </td>
                    </tr>
                <?php endforeach ?>

            </table>
        </div>
   








</body>

</html>