<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./library/style.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <meta name="author" content="Florian Moreno">
    <title>Résumé Nazca </title>
</head>

<body>
    <header>
        <h1 class="tittle2"><img class="imgSize2" src="./img/icone2.png" alt="Snake logo"> Résumé Nazca <img class="imgSize2" src="./img/icone.png" alt="Snake logo"></h1>
    </header>

    <div class="box2">
        <select name="type" class="font">
            <option value="all">Tous</option>
            <option value="Snatch">Snatch</option>
            <option value="Nazca" selected>Nazca</option>
            <option value="Snow">Snow</option>
        </select>
    </div>

    <div class="border">
        <div class="type2">Ses derniers repas :</div>
        <table>

            <tr class="array">
                <th>Date</th>
                <th>Type</th>
            </tr>

            <tr class="array">
                <td>01/01/2020</td>
                <td>Rat moyen</td>
            </tr>

            <tr class="array">
                <td>08/01/2020</td>
                <td>Rat adulte</td>
            </tr>

            <tr class="array">
                <td>12/01/2020</td>
                <td>Rat adulte</td>
            </tr>
        </table>
    </div>

    <div class="border">
        <div class="type2"> Son poids :</div>
    </div>

    <div class="graphSize">
        <canvas id="myChart"></canvas>
    </div>
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'line',

            // The data for our dataset
            data: {
                labels: ['23/02/2019', '29/05/2019', '25/07/2019', '11/08/2019', '29/10/19', '11/11/2019'],
                datasets: [{
                    label: 'Evolution Nazca',
                    fill: 'false',
                    spanGaps: 'true',
                    borderColor: 'rgb(16, 14, 161)',
                    data: [792, 801, NaN, NaN, 1060, NaN]
                }]
            },

            // Configuration options go here
            options: {}
        });
    </script>

</body>

</html>